"""Add job_role to Reference

Revision ID: 950be85e5218
Revises: 
Create Date: 2026-03-08 11:22:10.400501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950be85e5218'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('references', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_role', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('references', schema=None) as batch_op:
        batch_op.drop_column('job_role')

    # ### end Alembic commands ###
